apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-api-golang
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: k8s-api-job-sa
      containers:
      - name: k8s-api-golang
        image: lmagana92/k8s-api-golang:dev
        command: ['bash', '-c', 'sleep 5; /k8s-job/main -sleepTime=5']
      restartPolicy: Never