apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-api-golang
spec:
  template:
    spec:
      serviceAccountName: k8s-api-job-sa
      containers:
      - name: k8s-api-golang
        image: lmagana92/k8s-api-golang:timeout
        command: ["/k8s-job/main", "-sleepTime=15"]
      restartPolicy: Never